name: Auto Deploy to Server
on:
  push:
    branches: [ master ]  # 监听 main 分支的推送

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server
        run: |
         # 显示调试信息
         echo "尝试连接到服务器..."
         ssh -vvv -o StrictHostKeyChecking=no \
            ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} \
            "echo '连接成功！'"
         # 检查公钥是否加载
         ssh-add -L
         
      - name: 连接服务器并执行命令
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}# 服务器的 IP 或域名
          username: ${{ secrets.SERVER_USER }}# 服务器登录用户
          key: ${{ secrets.SSH_PRIVATE_KEY }} # 服务器 SSH 私钥内容
          script: |
            cd /www/wwwroot/test0309/think  # 修改为服务器上的项目路径
            git pull origin master      # 拉取最新代码
            # 可选：执行构建命令（如 npm install、mvn package 等）
            # npm install
            # npm run build
      

